CREATE TABLE IF NOT EXISTS movies(
	id bigserial PRIMARY KEY,
	created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
	title TEXT NOT NULL,
	YEAR INTEGER NOT NULL,
	runtime INTEGER NOT NULL,
	genres text[] NOT NULL,
	version integer NOT NULL DEFAULT 1
);
